spring.application.name=logs_loki

# Cấu hình log mức INFO mặc định, DEBUG cho app
logging.level.root=INFO
logging.level.nobrain.logs_loki=DEBUG

# Cấu hình đẩy Tomcat Access Log ra console dưới dạng JSON
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/dev
server.tomcat.accesslog.prefix=stdout
server.tomcat.accesslog.suffix=
server.tomcat.accesslog.file-date-format=
# Lưu ý pattern được định dạng JSON, type="access" để phân biệt với log của ứng dụng
server.tomcat.accesslog.pattern={"type":"access", "clientip":"%a", "httpmethod":"%m", "status":"%s", "url":"%U", "duration":%D, "traceid":"%{traceId}r", "spanid":"%{spanId}r"}

# Bật tracing
management.tracing.sampling.probability=1.0
